export const userConstants = {
  USER_ME_REQUEST: "USER_ME_REQUEST",
  USER_ME_SUCCESS: "USER_ME_SUCCESS",
  USER_ME_FAILURE: "USER_ME_FAILURE",

  USER_DELETE_ME_REQUEST: "USER_DELETE_ME_REQUEST",
  USER_DELETE_ME_SUCCESS: "USER_DELETE_ME_SUCCESS",
  USER_DELETE_ME_FAILURE: "USER_DELETE_ME_FAILURE",

  USER_TOKEN_REQUEST: "USER_TOKEN_REQUEST",
  USER_TOKEN_SUCCESS: "USER_TOKEN_SUCCESS",
  USER_TOKEN_FAILURE: "USER_TOKEN_FAILURE",

  GET_PROVIDER_LOGIN_URL_REQUEST: "GET_PROVIDER_LOGIN_URL_REQUEST",
  GET_PROVIDER_LOGIN_URL_SUCCESS: "GET_PROVIDER_LOGIN_URL_SUCCESS",
  GET_PROVIDER_LOGIN_URL_FAILURE: "GET_PROVIDER_LOGIN_URL_FAILURE",

  SEND_PROVIDER_LOGIN_CODE_REQUEST: "SEND_PROVIDER_LOGIN_CODE_REQUEST",
  SEND_PROVIDER_LOGIN_CODE_SUCCESS: "SEND_PROVIDER_LOGIN_CODE_SUCCESS",
  SEND_PROVIDER_LOGIN_CODE_FAILURE: "SEND_PROVIDER_LOGIN_CODE_FAILURE",

  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  USER_CONFIRM_REQUEST: "USER_CONFIRM_REQUEST",
  USER_CONFIRM_SUCCESS: "USER_CONFIRM_SUCCESS",
  USER_CONFIRM_FAILURE: "USER_CONFIRM_FAILURE",

  USER_FORGOT_REQUEST: "USER_FORGOT_REQUEST",
  USER_FORGOT_SUCCESS: "USER_FORGOT_SUCCESS",
  USER_FORGOT_FAILURE: "USER_FORGOT_FAILURE",

  USER_RESET_REQUEST: "USER_RESET_REQUEST",
  USER_RESET_SUCCESS: "USER_RESET_SUCCESS",
  USER_RESET_FAILURE: "USER_RESET_FAILURE",

  USER_GET_REQUEST: "USER_GET_REQUEST",
  USER_GET_SUCCESS: "USER_GET_SUCCESS",
  USER_GET_FAILURE: "USER_GET_FAILURE",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAILURE: "USER_UPDATE_FAILURE",

  USER_UPDATE_ME_REQUEST: "USER_UPDATE_ME_REQUEST",
  USER_UPDATE_ME_SUCCESS: "USER_UPDATE_ME_SUCCESS",
  USER_UPDATE_ME_FAILURE: "USER_UPDATE_ME_FAILURE",

  USER_UPDATE_ME_PASSWORD_REQUEST: "USER_UPDATE_ME_PASSWORD_REQUEST",
  USER_UPDATE_ME_PASSWORD_SUCCESS: "USER_UPDATE_ME_PASSWORD_SUCCESS",
  USER_UPDATE_ME_PASSWORD_FAILURE: "USER_UPDATE_ME_PASSWORD_FAILURE",

  GET_PROVIDER_CONNECT_URL_REQUEST: "GET_PROVIDER_CONNECT_URL_REQUEST",
  GET_PROVIDER_CONNECT_URL_SUCCESS: "GET_PROVIDER_CONNECT_URL_SUCCESS",
  GET_PROVIDER_CONNECT_URL_FAILURE: "GET_PROVIDER_CONNECT_URL_FAILURE",

  SEND_PROVIDER_CONNECT_CODE_REQUEST: "SEND_PROVIDER_CONNECT_CODE_REQUEST",
  SEND_PROVIDER_CONNECT_CODE_SUCCESS: "SEND_PROVIDER_CONNECT_CODE_SUCCESS",
  SEND_PROVIDER_CONNECT_CODE_FAILURE: "SEND_PROVIDER_CONNECT_CODE_FAILURE",

  DISCONNECT_PROVIDER_REQUEST: "DISCONNECT_PROVIDER_REQUEST",
  DISCONNECT_PROVIDER_SUCCESS: "DISCONNECT_PROVIDER_SUCCESS",
  DISCONNECT_PROVIDER_FAILURE: "DISCONNECT_PROVIDER_FAILURE",

  DELETE_USER_AVATAR_REQUEST: "DELETE_USER_AVATAR_REQUEST",
  DELETE_USER_AVATAR_SUCCESS: "DELETE_USER_AVATAR_SUCCESS",
  DELETE_USER_AVATAR_FAILURE: "DELETE_USER_AVATAR_FAILURE",
};
