export const cycleConstants = {
  CREATE_CYCLE_REQUEST: "CREATE_CYCLE_REQUEST",
  CREATE_CYCLE_SUCCESS: "CREATE_CYCLE_SUCCESS",
  CREATE_CYCLE_FAILURE: "CREATE_CYCLE_FAILURE",

  GET_CYCLES_REQUEST: "GET_CYCLES_REQUEST",
  GET_CYCLES_SUCCESS: "GET_CYCLES_SUCCESS",
  GET_CYCLES_FAILURE: "GET_CYCLES_FAILURE",

  DELETE_CYCLE_REQUEST: "DELETE_CYCLE_REQUEST",
  DELETE_CYCLE_SUCCESS: "DELETE_CYCLE_SUCCESS",
  DELETE_CYCLE_FAILURE: "DELETE_CYCLE_FAILURE",

  GET_CYCLES_BY_AUTHOR_ID_REQUEST: "GET_CYCLES_BY_AUTHOR_ID_REQUEST",
  GET_CYCLES_BY_AUTHOR_ID_SUCCESS: "GET_CYCLES_BY_AUTHOR_ID_SUCCESS",
  GET_CYCLES_BY_AUTHOR_ID_FAILURE: "GET_CYCLES_BY_AUTHOR_ID_FAILURE",
};
