export const chapterConstants = {
  CREATE_CHAPTER_REQUEST: "CREATE_CHAPTER_REQUEST",
  CREATE_CHAPTER_SUCCESS: "CREATE_CHAPTER_SUCCESS",
  CREATE_CHAPTER_FAILURE: "CREATE_CHAPTER_FAILURE",

  GET_CHAPTERS_BY_BOOK_ID_REQUEST: "GET_CHAPTERS_BY_BOOK_ID_REQUEST",
  GET_CHAPTERS_BY_BOOK_ID_SUCCESS: "GET_CHAPTERS_BY_BOOK_ID_SUCCESS",
  GET_CHAPTERS_BY_BOOK_ID_FAILURE: "GET_CHAPTERS_BY_BOOK_ID_FAILURE",

  CHANGE_CHAPTER_INDEX_REQUEST: "CHANGE_CHAPTER_INDEX_REQUEST",
  CHANGE_CHAPTER_INDEX_SUCCESS: "CHANGE_CHAPTER_INDEX_SUCCESS",
  CHANGE_CHAPTER_INDEX_FAILURE: "CHANGE_CHAPTER_INDEX_FAILURE",

  EDIT_CHAPTER_REQUEST: "EDIT_CHAPTER_REQUEST",
  EDIT_CHAPTER_SUCCESS: "EDIT_CHAPTER_SUCCESS",
  EDIT_CHAPTER_FAILURE: "EDIT_CHAPTER_FAILURE",

  DELETE_CHAPTER_REQUEST: "DELETE_CHAPTER_REQUEST",
  DELETE_CHAPTER_SUCCESS: "DELETE_CHAPTER_SUCCESS",
  DELETE_CHAPTER_FAILURE: "DELETE_CHAPTER_FAILURE",
};
