export const booksConstants = {
  CREATE_BOOK_REQUEST: "CREATE_BOOK_REQUEST",
  CREATE_BOOK_SUCCESS: "CREATE_BOOK_SUCCESS",
  CREATE_BOOK_FAILURE: "CREATE_BOOK_FAILURE",

  GET_BOOK_REQUEST: "GET_BOOK_REQUEST",
  GET_BOOK_SUCCESS: "GET_BOOK_SUCCESS",
  GET_BOOK_FAILURE: "GET_BOOK_FAILURE",

  UPDATE_BOOK_PROPERTIES_REQUEST: "UPDATE_BOOK_PROPERTIES_REQUEST",
  UPDATE_BOOK_PROPERTIES_SUCCESS: "UPDATE_BOOK_PROPERTIES_SUCCESS",
  UPDATE_BOOK_PROPERTIES_FAILURE: "UPDATE_BOOK_PROPERTIES_FAILURE",

  GET_BOOK_PROPERTIES_REQUEST: "GET_BOOK_PROPERTIES_REQUEST",
  GET_BOOK_PROPERTIES_SUCCESS: "GET_BOOK_PROPERTIES_SUCCESS",
  GET_BOOK_PROPERTIES_FAILURE: "GET_BOOK_PROPERTIES_FAILURE",

  RENAME_BOOK_REQUEST: "RENAME_BOOK_REQUEST",
  RENAME_BOOK_SUCCESS: "RENAME_BOOK_SUCCESS",
  RENAME_BOOK_FAILURE: "RENAME_BOOK_FAILURE",

  DELETE_BOOK_REQUEST: "DELETE_BOOK_REQUEST",
  DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_BOOK_FAILURE: "DELETE_BOOK_FAILURE",

  CHANGE_PUBLISH_STATUS_BOOK_REQUEST: "CHANGE_PUBLISH_STATUS_BOOK_REQUEST",
  CHANGE_PUBLISH_STATUS_BOOK_SUCCESS: "CHANGE_PUBLISH_STATUS_BOOK_SUCCESS",
  CHANGE_PUBLISH_STATUS_BOOK_FAILURE: "CHANGE_PUBLISH_STATUS_BOOK_FAILURE",

  CHANGE_COMPLETE_STATUS_BOOK_REQUEST: "CHANGE_COMPLETE_STATUS_BOOK_REQUEST",
  CHANGE_COMPLETE_STATUS_BOOK_SUCCESS: "CHANGE_COMPLETE_STATUS_BOOK_SUCCESS",
  CHANGE_COMPLETE_STATUS_BOOK_FAILURE: "CHANGE_COMPLETE_STATUS_BOOK_FAILURE",

  EDIT_PRICE_BOOK_REQUEST: "EDIT_PRICE_BOOK_REQUEST",
  EDIT_PRICE_BOOK_SUCCESS: "EDIT_PRICE_BOOK_SUCCESS",
  EDIT_PRICE_BOOK_FAILURE: "EDIT_PRICE_BOOK_FAILURE",

  REMOVE_BOOK_COVER_REQUEST: "REMOVE_BOOK_COVER_REQUEST",
  REMOVE_BOOK_COVER_SUCCESS: "REMOVE_BOOK_COVER_SUCCESS",
  REMOVE_BOOK_COVER_FAILURE: "REMOVE_BOOK_COVER_FAILURE",

  GET_BOOK_LOG_REQUEST: "GET_BOOK_LOG_REQUEST",
  GET_BOOK_LOG_SUCCESS: "GET_BOOK_LOG_SUCCESS",
  GET_BOOK_LOG_FAILURE: "GET_BOOK_LOG_FAILURE",
};
